### ISSUE TITLE
生成gif时，报错

### ISSUE THREAD

**Issue by zhudaoruyi** [pyecharts/pyecharts-snapshot#44]
```
Generating file ...
Traceback (most recent call last):
  File "d:\anaconda3\envs\venv37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\envs\venv37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\envs\venv37\Scripts\snapshot.exe\__main__.py", line 7, in <module>
  File "d:\anaconda3\envs\venv37\lib\site-packages\pyecharts_snapshot\main.py", line 86, in main
    asyncio.get_event_loop().run_until_complete(_main())
  File "d:\anaconda3\envs\venv37\lib\asyncio\base_events.py", line 583, in run_until_complete
    return future.result()
  File "d:\anaconda3\envs\venv37\lib\site-packages\pyecharts_snapshot\main.py", line 109, in _main
    file_name, output, delay=delay, pixel_ratio=pixel_ratio
  File "d:\anaconda3\envs\venv37\lib\site-packages\pyecharts_snapshot\main.py", line 130, in make_a_snapshot
    file_name, file_type, pixel_ratio, delay
  File "d:\anaconda3\envs\venv37\lib\site-packages\pyecharts_snapshot\main.py", line 169, in async_make_snapshot
    return await get_echarts(to_file_uri(html_path), snapshot_js)
  File "d:\anaconda3\envs\venv37\lib\site-packages\pyecharts_snapshot\main.py", line 175, in get_echarts
    await page.goto(url)
  File "d:\anaconda3\envs\venv37\lib\site-packages\pyppeteer\page.py", line 862, in goto
    raise error
pyppeteer.errors.TimeoutError: Navigation Timeout Exceeded: 30000 ms exceeded.
```

**Comment by chfw** [comment]
命令行是什么？

**Comment by zhudaoruyi** [comment]
```
snapshot index.html gif
```

**Comment by chfw** [comment]
Index.html 在当前目录吗？

**Comment by zhudaoruyi** [comment]
在
