### ISSUE TITLE
pyppeteer.errors.BrowserError: Browser closed unexpectedly:

### ISSUE THREAD

**Issue by Rease123** [pyecharts/pyecharts-snapshot#46]
When I run a html file using "snapshot render.html svg", what are the some errors ? How to resovle it?

Generating file ...
Traceback (most recent call last):
  File "/usr/local/bin/snapshot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pyecharts_snapshot/main.py", line 86, in main
    asyncio.get_event_loop().run_until_complete(_main())
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/pyecharts_snapshot/main.py", line 109, in _main
    file_name, output, delay=delay, pixel_ratio=pixel_ratio
  File "/usr/local/lib/python3.7/site-packages/pyecharts_snapshot/main.py", line 130, in make_a_snapshot
    file_name, file_type, pixel_ratio, delay
  File "/usr/local/lib/python3.7/site-packages/pyecharts_snapshot/main.py", line 169, in async_make_snapshot
    return await get_echarts(to_file_uri(html_path), snapshot_js)
  File "/usr/local/lib/python3.7/site-packages/pyecharts_snapshot/main.py", line 173, in get_echarts
    browser = await launch()
  File "/usr/local/lib/python3.7/site-packages/pyppeteer/launcher.py", line 305, in launch
    return await Launcher(options, **kwargs).launch()
  File "/usr/local/lib/python3.7/site-packages/pyppeteer/launcher.py", line 166, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/usr/local/lib/python3.7/site-packages/pyppeteer/launcher.py", line 225, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:

**Comment by sunhailin-Leo** [comment]
@Rease123 
* Are you running at Linux?
* If you are running at Linux, you should change the source code for `await pyppeteer.launch(options={'args': ['--no-sandbox']})`

**Comment by vsoch** [comment]
Hi! I just hit this issue (on Linux) - when you say "change the source code" could you point me to where this is?

**Comment by vsoch** [comment]
I suspect here? https://github.com/pyecharts/pyecharts-snapshot/blob/ca916c0af23308c52eec56e75f88f23d98ff71f5/pyecharts_snapshot/main.py#L171-L178

Would you accept a pull request to add a  command line argument for `--no-sandbox`? I think there are likely a lot of Linux users (and this would be useful for them too!)

**Comment by ZongzhiWu** [comment]
@vsoch Have you solved this problem on linux?

**Comment by vsoch** [comment]
I didn't pursue it further because there was no response above, and wound up using plotly in Python with some html templates and it produced the chart I was looking for. https://github.com/vsoch/citelang/blob/5b0fe38553afd90b19bfe918ca7b5ea56d5b513d/citelang/main/badge/__init__.py#L9
