### ISSUE TITLE
Can sankey plot be converted to vectorgraph like pdf or SVG file?

### ISSUE THREAD

**Issue by ZongzhiWu** [pyecharts/pyecharts-snapshot#51]
Vector graphics are essential for organizing the figures in manuscript. Can sankey plot be converted to vectorgraph like pdf or SVG file? Thanks a lot!

**Comment by ZongzhiWu** [comment]
**When I run the command 'snapshot sankey.html svg', I come across the following bug:**
Generating file ...
Traceback (most recent call last):
  File "/gpfs/share/home/2201112334/miniconda3/envs/pyechart/bin/snapshot", line 8, in <module>
    sys.exit(main())
  File "/gpfs/share/home/2201112334/miniconda3/envs/pyechart/lib/python3.7/site-packages/pyecharts_snapshot/main.py", line 86, in main
    asyncio.get_event_loop().run_until_complete(_main())
  File "/gpfs/share/home/2201112334/miniconda3/envs/pyechart/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/gpfs/share/home/2201112334/miniconda3/envs/pyechart/lib/python3.7/site-packages/pyecharts_snapshot/main.py", line 109, in _main
    file_name, output, delay=delay, pixel_ratio=pixel_ratio
  File "/gpfs/share/home/2201112334/miniconda3/envs/pyechart/lib/python3.7/site-packages/pyecharts_snapshot/main.py", line 130, in make_a_snapshot
    file_name, file_type, pixel_ratio, delay
  File "/gpfs/share/home/2201112334/miniconda3/envs/pyechart/lib/python3.7/site-packages/pyecharts_snapshot/main.py", line 169, in async_make_snapshot
    return await get_echarts(to_file_uri(html_path), snapshot_js)
  File "/gpfs/share/home/2201112334/miniconda3/envs/pyechart/lib/python3.7/site-packages/pyecharts_snapshot/main.py", line 173, in get_echarts
    browser = await launch()
  File "/gpfs/share/home/2201112334/miniconda3/envs/pyechart/lib/python3.7/site-packages/pyppeteer/launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "/gpfs/share/home/2201112334/miniconda3/envs/pyechart/lib/python3.7/site-packages/pyppeteer/launcher.py", line 168, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/gpfs/share/home/2201112334/miniconda3/envs/pyechart/lib/python3.7/site-packages/pyppeteer/launcher.py", line 227, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:
